
baseURL = "/"

# set this option to browse files in public/ locally
# e.g. by building with `env HUGO_RELATIVEURLS=1  hugo`
#relativeURLS = true

languageCode = "en-us"
title = "ErUM-IDT"
theme = "hugo-lithium-theme"

[params.logo]
  url = "/idt-logo.png"
  width = 50
  height = 50
  alt = "Logo"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1
[[menu.main]]
  name = "Partners"
  url = "/partners/"
  weight = 2
[[menu.main]]
  name = "Research Areas"
  url = "/research-areas/"
  weight = 3
[[menu.main]]
  name = "Activities"
  url = "/activities/"
  weight = 4
[[menu.main]]
  name = "Publications and Talks"
  url = "/publications/"
  weight = 5
  parent = "Activities"
[[menu.main]]
  name = "Meetings and Workshops"
  url = "/meetings/"
  weight = 6
  parent = "Activities"
[[menu.main]]
  name = "Logo"
  url = "/logo/"
  weight = 7
